GET http://127.0.0.1:5000/holamundo

###
POST http://127.0.0.1:5000/saludo?nombre=Mauro

###
GET http://127.0.0.1:5000/getRightWord

###
GET http://127.0.0.1:5000/getWordState


###
POST http://127.0.0.1:5000/riskWord?riskedWord=melon


###
POST http://127.0.0.1:5000/riskedLetter?riskedLetter=c


###
GET http://127.0.0.1:5000/getRiskedLetters



###
POST  http://127.0.0.1:5000/startGame