
###
POST http://127.0.0.1:10000/saludo?nombre=Mauro

###
GET http://127.0.0.1:10000/getRightWord

###
GET http://127.0.0.1:10000/getWordState


###
POST http://127.0.0.1:10000/riskWord?riskedWord=melon


###
POST http://127.0.0.1:10000/riskedLetter?riskedLetter=c


###
GET http://127.0.0.1:10000/getRiskedLetters



###
POST  http://127.0.0.1:10000/startGame